name: clockey
description: A sample command-line application.
version: 2.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  cron: ^0.6.0
  envied: ^0.5.3
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  hive: ^2.2.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  nyxx: ^6.0.3
  nyxx_commands: ^6.0.2
  nyxx_extensions: ^4.1.0
  puppeteer: ^3.6.0
  supabase: ^2.0.2
  tabular: ^0.6.3+1

# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.7
  envied_generator: ^0.5.3
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
