name: clockey
description: A sample command-line application.
version: 2.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  envied: ^0.5.4+1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.2
  get_it: ^7.7.0
  hive: ^2.2.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  nyxx: ^6.3.0
  nyxx_commands: ^6.0.2
  nyxx_extensions: ^4.1.0
  supabase: ^2.2.3
  tabular: ^0.6.3+1

# path: ^1.8.0
dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.7

dependency_overrides:
  nyxx_extensions:
    git:
      url: https://github.com/nyxx-discord/nyxx_extensions.git
      ref: dev
  nyxx:
    git:
      url: https://github.com/nyxx-discord/nyxx.git
      ref: dev

publish_to: none
